### ISSUE TITLE
Commit adds reminder functionality, but reminder dissappears

### ISSUE THREAD

**Issue by doomed-theory** [doomed-theory/HilltopApp-Mac#2]
commit #dcd6991c2d07b563747934b2eb0755f9c52dd205 adds reminder functionality to the electron version, but it does not have a way for the reminder to stay open. Reminders which close so fast may not be particularly useful to end users, as they go by so fast they may not see. Reminders need to stay visible  longer

**Comment by mrniceguy127** [comment]
Having a lot of trouble finding a way to keep them persistent on a Mac let alone other platforms. Also was thinking of adding an alerts tab.
